
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'commandALL AT AVAILABLE BOOK CANCEL CLASS_TYPE CONFIRM DATE EVENTS FOR FROM HELP IN LIST ON PAY QUANTITY RESERVATION SCHEDULE SHOW STATUS STRING TICKETS TIME TOcommand : list_command\n| book_command\n| confirm_command\n| pay_command\n| cancel_command\n| show_command\n| help_commandhelp_command : HELP\n| HELP STRINGlist_command : LIST STRING SCHEDULE FROM STRING TO STRING ON DATE AT TIME\n| LIST AVAILABLE STRING IN STRING\n| LIST AVAILABLE EVENTS IN STRING\n| LIST TICKETS FOR STRING\n| LIST TICKETS FOR STRING ON DATEbook_command : BOOK STRING FROM STRING TO STRING ON DATE AT TIME FOR STRING FOR QUANTITY\n| BOOK STRING AT STRING ON DATE AT TIME FOR STRING IN CLASS_TYPE FOR QUANTITY\n| BOOK STRING ON DATE AT TIME FOR STRING FOR QUANTITY\n| BOOK STRING FROM DATE TO DATE AT TIME FOR STRING FOR QUANTITY\n| BOOK QUANTITY STRING FROM TIME TO TIME ON DATE FOR STRINGconfirm_command : CONFIRM QUANTITY RESERVATION FOR STRING FOR STRING\n| CONFIRM ALL RESERVATION FOR STRINGpay_command : PAY FOR QUANTITY STRING RESERVATION FOR STRING\n| PAY FOR ALL RESERVATION FOR STRING\n| PAY ALL RESERVATION FOR STRINGcancel_command : CANCEL QUANTITY STRING RESERVATION FOR STRING\n| CANCEL ALL RESERVATION FOR STRINGshow_command : SHOW ALL STATUS RESERVATION FOR STRING\n| SHOW ALL RESERVATION FOR STRING\n| SHOW STRING RESERVATION FOR STRING'
    
_lr_action_items = {'LIST':([0,],[9,]),'BOOK':([0,],[10,]),'CONFIRM':([0,],[11,]),'PAY':([0,],[12,]),'CANCEL':([0,],[13,]),'SHOW':([0,],[14,]),'HELP':([0,],[15,]),'$end':([1,2,3,4,5,6,7,8,15,29,51,68,69,77,80,82,84,85,87,95,96,97,104,105,121,124,128,130,134,135,],[0,-1,-2,-3,-4,-5,-6,-7,-8,-9,-13,-11,-12,-21,-24,-26,-28,-29,-14,-23,-25,-27,-20,-22,-17,-10,-19,-18,-15,-16,]),'STRING':([9,10,14,15,17,20,25,33,34,36,40,48,49,50,57,58,61,63,65,66,71,79,81,83,86,93,94,101,114,116,123,125,],[16,19,28,29,31,37,43,51,52,55,59,67,68,69,76,77,80,82,84,85,88,95,96,97,98,104,105,109,120,122,128,129,]),'AVAILABLE':([9,],[17,]),'TICKETS':([9,],[18,]),'QUANTITY':([10,11,13,23,115,126,132,133,],[20,21,25,40,121,130,134,135,]),'ALL':([11,12,13,14,23,],[22,24,26,27,41,]),'FOR':([12,18,38,39,42,44,46,47,60,62,64,76,78,90,108,109,110,117,119,120,129,131,],[23,33,57,58,61,63,65,66,79,81,83,93,94,101,114,115,116,123,125,126,132,133,]),'SCHEDULE':([16,],[30,]),'EVENTS':([17,],[32,]),'FROM':([19,30,37,],[34,48,56,]),'AT':([19,54,89,91,107,112,],[36,73,100,102,113,118,]),'ON':([19,51,55,88,98,103,],[35,70,74,99,106,111,]),'RESERVATION':([21,22,24,26,27,28,41,43,45,59,],[38,39,42,44,46,47,60,62,64,78,]),'STATUS':([27,],[45,]),'IN':([31,32,122,],[49,50,127,]),'DATE':([34,35,70,72,74,99,106,111,],[53,54,87,89,91,107,112,117,]),'TO':([52,53,67,75,],[71,72,86,92,]),'TIME':([56,73,92,100,102,113,118,],[75,90,103,108,110,119,124,]),'CLASS_TYPE':([127,],[131,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'command':([0,],[1,]),'list_command':([0,],[2,]),'book_command':([0,],[3,]),'confirm_command':([0,],[4,]),'pay_command':([0,],[5,]),'cancel_command':([0,],[6,]),'show_command':([0,],[7,]),'help_command':([0,],[8,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> command","S'",1,None,None,None),
  ('command -> list_command','command',1,'p_command','core.py',12),
  ('command -> book_command','command',1,'p_command','core.py',13),
  ('command -> confirm_command','command',1,'p_command','core.py',14),
  ('command -> pay_command','command',1,'p_command','core.py',15),
  ('command -> cancel_command','command',1,'p_command','core.py',16),
  ('command -> show_command','command',1,'p_command','core.py',17),
  ('command -> help_command','command',1,'p_command','core.py',18),
  ('help_command -> HELP','help_command',1,'p_help_command','core.py',22),
  ('help_command -> HELP STRING','help_command',2,'p_help_command','core.py',23),
  ('list_command -> LIST STRING SCHEDULE FROM STRING TO STRING ON DATE AT TIME','list_command',11,'p_list_command','core.py',29),
  ('list_command -> LIST AVAILABLE STRING IN STRING','list_command',5,'p_list_command','core.py',30),
  ('list_command -> LIST AVAILABLE EVENTS IN STRING','list_command',5,'p_list_command','core.py',31),
  ('list_command -> LIST TICKETS FOR STRING','list_command',4,'p_list_command','core.py',32),
  ('list_command -> LIST TICKETS FOR STRING ON DATE','list_command',6,'p_list_command','core.py',33),
  ('book_command -> BOOK STRING FROM STRING TO STRING ON DATE AT TIME FOR STRING FOR QUANTITY','book_command',14,'p_book_command','core.py',61),
  ('book_command -> BOOK STRING AT STRING ON DATE AT TIME FOR STRING IN CLASS_TYPE FOR QUANTITY','book_command',14,'p_book_command','core.py',62),
  ('book_command -> BOOK STRING ON DATE AT TIME FOR STRING FOR QUANTITY','book_command',10,'p_book_command','core.py',63),
  ('book_command -> BOOK STRING FROM DATE TO DATE AT TIME FOR STRING FOR QUANTITY','book_command',12,'p_book_command','core.py',64),
  ('book_command -> BOOK QUANTITY STRING FROM TIME TO TIME ON DATE FOR STRING','book_command',11,'p_book_command','core.py',65),
  ('confirm_command -> CONFIRM QUANTITY RESERVATION FOR STRING FOR STRING','confirm_command',7,'p_confirm_command','core.py',128),
  ('confirm_command -> CONFIRM ALL RESERVATION FOR STRING','confirm_command',5,'p_confirm_command','core.py',129),
  ('pay_command -> PAY FOR QUANTITY STRING RESERVATION FOR STRING','pay_command',7,'p_pay_command','core.py',147),
  ('pay_command -> PAY FOR ALL RESERVATION FOR STRING','pay_command',6,'p_pay_command','core.py',148),
  ('pay_command -> PAY ALL RESERVATION FOR STRING','pay_command',5,'p_pay_command','core.py',149),
  ('cancel_command -> CANCEL QUANTITY STRING RESERVATION FOR STRING','cancel_command',6,'p_cancel_command','core.py',174),
  ('cancel_command -> CANCEL ALL RESERVATION FOR STRING','cancel_command',5,'p_cancel_command','core.py',175),
  ('show_command -> SHOW ALL STATUS RESERVATION FOR STRING','show_command',6,'p_show_command','core.py',194),
  ('show_command -> SHOW ALL RESERVATION FOR STRING','show_command',5,'p_show_command','core.py',195),
  ('show_command -> SHOW STRING RESERVATION FOR STRING','show_command',5,'p_show_command','core.py',196),
]
